### ISSUE TITLE
How to properly implement debounce 

### ISSUE THREAD

**Issue by 0x67** [ivan-topp/y-socket.io#1]
Using your both of your example in for the client and server I'm able to setup a simple debounce to update the `yMap`.

Here's the snippet, because the rest of the code is exactly the same as your client example. Server side code is not modified.
```
const  handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
	setInput(e.target.value);
};

// Input Element
<input
	value={input}
	onChange={handleChange}
	// onChange={(e) =>
	// doc.getMap("data").set("input", e.target.value ?? "")
	// }
/>
```

Debounce on every input change using lodash-debounce
```
useEffect(() => {
	debouncedInput(input);
	return () => {
		debouncedInput.cancel();
	};
}, [input]);

const  debouncedInput = debounce((input) => {
	doc?.getMap("data").set("input", input);
}, 1000);
```

But I think that cause race condition:
1. Client A types something
2. Client B receive the update from client A, but since client B itself receives an update, the debounce function is triggered
3. If client B debounce happened when client A is still typing something, client A text get reverted to client B version

I hope I'm clear enough, if not I can provide an example repo. 

Some guidance or insight on this is very helpful

**Comment by ivan-topp** [comment]
@0x67 Hi, I have just tried the code you present and the problem in point 3 actually occurs.

This occurs because YMap data type operations are designed to maintain correct synchronization between properties that are added to or removed from the YMap. The example was created just to show that YJS documents sync correctly over websockets with socket.io, so I used a plain, normal string instead of YText on YMap's 'input' key. In fact, in this case if two users type at the same time in the example, when the value of the input is modified by the input of client A, regardless of where in the text the cursor is located by client B, when receiving a change from client A, client B's cursor will be placed at the end (most rich text editors that currently support YJS and cursors, like Quill, handle cursor positioning and work with YText to resolve this).

I'm not a YJS expert, but I think for what you're looking for it's best to use the YText data type and its operations, implementing logic in the input of the example to insert or delete text at certain places in the YText. Since this way you can send operations like, for example, client A inserted 'abc' at position 0 of the YText and client B inserted 'def' also at position 0, this would make the result either 'abcdef' or 'defabc' depending on which insert the operation was sent first.

I don't quite understand the context for wich you need to use debounce, but I think using YText with your operations correctly will allow you to solve the problem in point 3.

I hope I have been able to guide or help you.

PS: Do not forget to close this issue if you consider that the previous information is enough for you.

**Comment by ivan-topp** [comment]
@0x67 Hi, I have just tried the code you present and the problem in point 3 actually occurs.

This occurs because YMap data type operations are designed to maintain correct synchronization between properties that are added to or removed from the YMap. The example was created just to show that YJS documents sync correctly over websockets with socket.io, so I used a plain, normal string instead of YText on YMap's 'input' key. In fact, in this case if two users type at the same time in the example, when the value of the input is modified by the input of client A, regardless of where in the text the cursor is located by client B, when receiving a change from client A, client B's cursor will be placed at the end (most rich text editors that currently support YJS and cursors, like Quill, handle cursor positioning and work with YText to resolve this).

I'm not a YJS expert, but I think for what you're looking for it's best to use the YText data type and its operations, implementing logic in the input of the example to insert or delete text at certain places in the YText. Since this way you can send operations like, for example, client A inserted 'abc' at position 0 of the YText and client B inserted 'def' also at position 0, this would make the result either 'abcdef' or 'defabc' depending on which insert the operation was sent first.

I don't quite understand the context for wich you need to use debounce, but I think using YText with your operations correctly will allow you to solve the problem in point 3.

I hope I have been able to guide or help you. I remain attentive to your comments.

PS: Do not forget to close this issue if you consider that the previous information is enough for you.
